# Generated by Django 4.2.9 on 2024-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=75)),
                ("phone", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=25)),
                ("zipcode", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="record",
            name="installer_name",
            field=models.CharField(default="No Installer Yet", max_length=50),
        ),
        migrations.AddField(
            model_name="record",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("Waiting on Survey", "WAITING ON SURVEY"),
                    ("Waiting on Tou", "WAITING ON TOU"),
                    ("Waiting on Deposit", "WAITING ON DEPOSIT"),
                    ("Waiting on Installer", "WAITING ON INSTALLER"),
                    ("Waiting on Customer", "WAITING ON CUSTOMER"),
                    ("Waiting on Install Date", "WAITING ON INSTALL DATE"),
                    ("Install Completed", "INSTALL COMPLETED"),
                ],
                default="Waiting on Survey",
                max_length=50,
            ),
        ),
    ]
