# Generated by Django 4.2.9 on 2024-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_installer_record_installer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installer",
            name="license_number",
            field=models.CharField(default="Still Need!", max_length=50),
        ),
    ]
