# Generated by Django 4.2.9 on 2024-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_installer_license_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="project_tier",
            field=models.CharField(
                choices=[
                    ("Custom", "CUSTOM"),
                    ("Tier 1", "TIER 1"),
                    ("Tier 2", "TIER 2"),
                    ("Tier 3", "TIER 3"),
                    ("Tier 4", "TIER 4"),
                    ("Tier 5", "TIER 5"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
