# Generated by Django 4.2.9 on 2024-01-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_record_customer_price_record_installer_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="customer_price",
            field=models.IntegerField(default="-", null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="installer_price",
            field=models.IntegerField(default="-", null=True),
        ),
    ]
