# Generated by Django 4.2.9 on 2024-01-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0016_rename_customer_permit_price_record_customer_permit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="customer_permit",
            field=models.IntegerField(default=" ", null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="customer_price",
            field=models.IntegerField(default=" ", null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="installer_permit",
            field=models.IntegerField(default=" ", null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="installer_price",
            field=models.IntegerField(default=" ", null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="project_tier",
            field=models.CharField(
                choices=[
                    ("Custom", "CUSTOM"),
                    ("Tier 1", "TIER 1"),
                    ("Tier 2", "TIER 2"),
                    ("Tier 3", "TIER 3"),
                    ("Tier 4", "TIER 4"),
                    ("Tier 5", "TIER 5"),
                ],
                default=" ",
                max_length=50,
            ),
        ),
    ]
